import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Manrope } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";
import Refresher from "@/components/custom/Refresher";
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope"
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={cn(manrope.variable, "antialiased font-manrope bg-background")}
        >
          <Refresher>
            <Header />
            <Toaster closeButton richColors />
            <main>
              {children}
            </main>
          </Refresher>
        </body>
      </StoreProvider>
    </html>
  );
}
